services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whats-the-tab-web
    ports:
      - "8008:8008"
    volumes:
      - ./audios:/app/audios
      - ./midi:/app/midi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
