version: '3.3'

services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  django:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USE_GPU=false
    environment:
      - DJANGO_ENV=development
      - START_SERVER=true
      - START_REDIS=false
      - START_DRAMATIQ=false
    volumes:
      - .:/app
      - ./data/media:/app/src/mt3-transcription/musictranscription/media
      - ./data/static:/app/src/mt3-transcription/musictranscription/static
    ports:
      - "8008:8008"
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USE_GPU=false
    command: python /app/src/mt3-transcription/musictranscription/run_dramatiq.py transcribeapp.tasks
    environment:
      - DJANGO_ENV=development
      - START_SERVER=false
      - START_REDIS=false
      - START_DRAMATIQ=false
    volumes:
      - .:/app
      - ./data/media:/app/src/mt3-transcription/musictranscription/media
    depends_on:
      - redis
      - django
    restart: unless-stopped

volumes:
  redis_data: 