# Generated by Django 5.0.4 on 2024-04-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribeapp', '0003_audiomidi_audio_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomidi',
            name='current_segment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audiomidi',
            name='num_transcription_segments',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='audiomidi',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
