# Generated by Django 5.0.4 on 2024-05-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribeapp', '0004_audiomidi_current_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomidi',
            name='is_midi2wav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiomidi',
            name='midi_wav_file',
            field=models.FileField(blank=True, null=True, upload_to='midi_2_wav/'),
        ),
        migrations.AddField(
            model_name='audiomidi',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiomidi',
            name='num_transcription_segments',
            field=models.IntegerField(default=10),
        ),
    ]
