# Generated by Django 5.0.6 on 2024-05-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribeapp', '0007_alter_audiochunk_chunk_file_midichunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiomidi',
            name='is_midi2wav',
        ),
        migrations.RemoveField(
            model_name='audiomidi',
            name='midi_file',
        ),
        migrations.RemoveField(
            model_name='audiomidi',
            name='midi_wav_file',
        ),
        migrations.AddField(
            model_name='audiomidi',
            name='audio_chunk_length',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='audiomidi',
            name='num_transcription_segments',
            field=models.IntegerField(default=1),
        ),
    ]
