# Generated by Django 5.0.4 on 2024-04-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribeapp', '0002_audiomidi_created_at_audiomidi_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomidi',
            name='audio_filename',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
