# Generated by Django 5.0.4 on 2024-05-07 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribeapp', '0005_audiomidi_is_midi2wav_audiomidi_midi_wav_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_file', models.FileField(upload_to='audios/')),
                ('segment_index', models.IntegerField(default=0)),
                ('audio_midi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_chunks', to='transcribeapp.audiomidi')),
            ],
        ),
    ]
