# Generated by Django 5.0.4 on 2024-05-09 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribeapp', '0006_audiochunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiochunk',
            name='chunk_file',
            field=models.FileField(upload_to='audio_chunks/'),
        ),
        migrations.CreateModel(
            name='MIDIChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midi_file', models.FileField(upload_to='midi_chunks/')),
                ('segment_index', models.IntegerField(default=0)),
                ('audio_midi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midi_chunks', to='transcribeapp.audiomidi')),
            ],
        ),
    ]
