# Generated by Django 5.0.6 on 2026-02-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribeapp', '0008_remove_audiomidi_is_midi2wav_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midichunk',
            name='audio_midi',
        ),
        migrations.RemoveField(
            model_name='audiomidi',
            name='audio_chunk_length',
        ),
        migrations.RemoveField(
            model_name='audiomidi',
            name='current_segment',
        ),
        migrations.RemoveField(
            model_name='audiomidi',
            name='num_transcription_segments',
        ),
        migrations.AddField(
            model_name='audiomidi',
            name='midi_file',
            field=models.FileField(blank=True, null=True, upload_to='midi/'),
        ),
        migrations.DeleteModel(
            name='AudioChunk',
        ),
        migrations.DeleteModel(
            name='MIDIChunk',
        ),
    ]
