# Generated by Django 5.0.14 on 2026-02-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcribeapp', '0009_remove_midichunk_audio_midi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomidi',
            name='current_chunk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audiomidi',
            name='total_chunks',
            field=models.IntegerField(default=0),
        ),
    ]
