#!/bin/bash
# Script to upload PyTorch checkpoint to GitHub Release
# This provides instructions for manual upload since gh CLI is not installed

CHECKPOINT_FILE="src/mt3-transcription/pytorch_mt3/mt3_pytorch_checkpoint.pt"
CHECKPOINT_SIZE=$(du -h "$CHECKPOINT_FILE" | cut -f1)
RELEASE_TAG="v1.0-pytorch-checkpoint"
RELEASE_TITLE="PyTorch MT3 Model Checkpoint"

echo "========================================="
echo "GitHub Release Setup Instructions"
echo "========================================="
echo ""
echo "Checkpoint file: $CHECKPOINT_FILE"
echo "File size: $CHECKPOINT_SIZE"
echo ""
echo "To upload this checkpoint to GitHub Releases:"
echo ""
echo "1. Go to: https://github.com/osamja/whats-the-tab/releases/new"
echo ""
echo "2. Fill in the release form:"
echo "   - Tag version: $RELEASE_TAG"
echo "   - Release title: $RELEASE_TITLE"
echo "   - Description:"
echo "     ---"
echo "     PyTorch MT3 model checkpoint (175 MB)"
echo "     "
echo "     This is the converted PyTorch weights for the MT3 music transcription model."
echo "     The model is used for audio-to-MIDI transcription."
echo "     "
echo "     **Download URL:**"
echo "     \`https://github.com/osamja/whats-the-tab/releases/download/$RELEASE_TAG/mt3_pytorch_checkpoint.pt\`"
echo "     ---"
echo ""
echo "3. Upload the checkpoint file by dragging and dropping:"
echo "   $CHECKPOINT_FILE"
echo ""
echo "4. Click 'Publish release'"
echo ""
echo "5. After publishing, the checkpoint will be available at:"
echo "   https://github.com/osamja/whats-the-tab/releases/download/$RELEASE_TAG/mt3_pytorch_checkpoint.pt"
echo ""
echo "========================================="
